### ISSUE TITLE
dbt Hub README doesn't match the GitHub README format

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [dbt-labs/hub.getdbt.com#1583]
## Overview of the Issue
We are making updates to our dbt package READMEs to streamline the onboarding experience for first time package users. One of the updates is including our optional package configuration steps within an expandable section of the README. It seems to be that this section is interpreted within GitHub, but it loses all formatting within the dbt Hub site. See the comparisons below:
- [GitHub dbt_fivetran_log README](https://github.com/fivetran/dbt_fivetran_log/tree/v0.6.0/#optional-step-5-additional-configurations)
![image](https://user-images.githubusercontent.com/74217849/168908978-43b6600c-462d-4899-b71f-2da412b9e59d.png)

- [dbt Hub dbt_fivetran_log README](https://hub.getdbt.com/fivetran/fivetran_log/latest/)
![image](https://user-images.githubusercontent.com/74217849/168909090-a77fa3d9-e669-4168-8aa0-a03d97255458.png)

## Expected Outcome
The formatting and style within the dbt hub README matches that of GitHub

## Additional Notes
I noticed a few other formatting options don't translate across as well. For example the badges are all centered on GitHub and are strangely formatted within the dbt hub.

I am happy to contribute if possible to address this issue. Thanks!

**Comment by jasnonaz** [comment]
Hi Joe! Thanks for letting us know about this. It looks like there is definitely something funky going on with the README import. I'm going to connect with folks internally and see if we can get a fix for this prioritized.

**Comment by dbeatty10** [comment]
@fivetran-joemarkiewicz @b-per fixed a piece of this in #1780 so the toggle arrows are showing correctly now:

https://hub.getdbt.com/fivetran/fivetran_log/latest/
- <img width="400" alt="image" src="https://user-images.githubusercontent.com/44704949/185503155-23d281bb-42bb-4f26-8d2d-848b764cc971.png">

Content without Markdown headings look good:

- <img width="400" alt="image" src="https://user-images.githubusercontent.com/44704949/185503313-f76fd6ef-3124-474a-9861-42f94bbeb062.png">

But those containing Markdown headings weren't fixed by this change:
- <img width="400" alt="image" src="https://user-images.githubusercontent.com/44704949/185503819-00bdecec-aee6-4eae-a67d-b5ddb522a02d.png">

There is some explanation in #1780:

> This is still not 100% perfect, especially when special formatting is done within the details tag, but based on my troubleshooting, this is a limitation of [kramdown](https://github.com/gettalong/kramdown), the MD renderer used in middleman. ([Here is a demo](https://kramdown-sandbox.herokuapp.com/) of kramdown if someone wants to try specific behavior). But I feel that this is still a pretty big improvement compare to the current behavior.

As you mentioned, the badges show up stacked:
- <img width="400" alt="image" src="https://user-images.githubusercontent.com/44704949/185504012-23255113-c183-464f-8717-67b59bd30d6e.png">

Rather than side-by-side and centered:
- <img width="400" alt="image" src="https://user-images.githubusercontent.com/44704949/185504074-f445b8ea-960b-4d22-95e0-db2e9c803f6d.png">

**Comment by dbeatty10** [comment]
@fivetran-joemarkiewicz just merged another contribution from @b-per -- check it out!
https://hub.getdbt.com/fivetran/fivetran_log/latest/

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/44704949/185606116-89892416-5b13-4767-a5e4-426843e42bbe.png">

**Comment by fivetran-joemarkiewicz** [comment]
@dbeatty10 you read my mind as I was just looking into this yesterday! 

I just took a look at the expanding functionality looks great 🎉. I also agree with the above statement that while the badges still show as stacked, it is a huge improvement and allows for a good user experience. The stacking of the badges is minor in my opinion whereas the collapse issue was bigger.

With this, we will start leveraging the collapsable pieces into our README's. Thanks for your and @b-per help on this 🙏

**Comment by dbeatty10** [comment]
Considering this resolved by #1780 and #1786.

@fivetran-joemarkiewicz we can open new issues if you run into other formatting issues.
